import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { ReactNode } from "react";
import Image from 'next/image';
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { ThemeProvider } from "@/components/theme-provider";
import { dark } from '@clerk/themes';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <ClerkProvider
    appearance={{
      baseTheme: dark,

      layout: {
        shimmer: true,
        animations: true,
      }
  }}>
      <html lang="en" suppressHydrationWarning={true}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
        <body className="flex justify-center items-center">
          <main className="flex-col h-screen items-center justify-center px-5 py-10">
            <div className="flex max-w-4xl border-2 rounded-lg bg-light-500 shadow-lg sm:flex-row">
            
              <section className="flex flex-col items-center justify-center p-10 sm:w-1/2">
                {children}
              </section>

              <section className="sm:block">
                <Image
                  src="/images/auth-illustration.png"
                  alt="auth illustration"
                  width={800}
                  height={800}
                  className="h-full object-cover"
                />
              </section>

            </div>
          </main>
        </body>
        </ThemeProvider>
      </html>
    </ClerkProvider>
  );
}
